### ISSUE TITLE
Generate secure JWT secret if user does not provide one in environment configuration

### ISSUE THREAD

**Issue by akstuhl** [performant-software/neatline-omeka-s#16]
As a Neatline developer, I want to have the option to set and view the secret key that will be used to encode and decode JWTs. If I've set an environment variable in my Omeka S server configuration called 'NEATLINE_JWT_SECRET', its value should be used as a secret.

As a Neatline user, I want to be able to install and use the Neatline module for Omeka S without having to learn about JWT or edit my server configuration. The module should, if I haven't provided one in the environment configuration, generate a secure pseudo-random string and store it in Omeka's global settings to serve as the secret key for JWT actions.

**Comment by feralresearch** [comment]
Per convo with Jamie: 

P1, do it...

P2, document process, augment with UI notice as necessary

**Comment by jamiefolsom** [comment]
Closing as covered in a later PR.
