### ISSUE TITLE
Provide and document a streamlined installation workflow

### ISSUE THREAD

**Issue by akstuhl** [performant-software/neatline-omeka-s#24]
As a Neatline developer, I want to be able to quickly set up a local instance of Omeka S with the Neatline module and its included single page application in order to make changes to the back-end Omeka module and/or the front-end application.

A Docker-based approach could provide a quick universal setup for all three components: https://github.com/scholarslab/neatline-omeka-s-docker

One issue for the development setup is how to maintain the usefulness of the create-react-app features (e.g. dynamic reloading) while also providing the ability to view the same version of front-end application rendered in its Omeka view container.

**Comment by jamiefolsom** [comment]
https://github.com/scholarslab/neatline-omeka-s-docker is a good solution for quick setup, and I've got a PR open to update to latest neatline-3 master. I will do that periodically. Stand alone development gets you the create-react-app goodness, if you need it.
