### ISSUE TITLE
Exhibit default map view and related settings

### ISSUE THREAD

**Issue by eam5** [performant-software/neatline-omeka-s#59]
I can't see a way to set a default map view for an exhibit and related settings. Included screenshot of exhibit setting options from previous version for reference. Related issue for record items as well- but the exhibit default map view is critical. 

<img width="409" alt="screen shot 2019-02-21 at 9 48 34 am" src="https://user-images.githubusercontent.com/2805368/53177437-0f675780-35be-11e9-859b-19c073a37ca3.png">

**Comment by akstuhl** [comment]
This correctly foregrounds the need for implementation of exhibit view settings in the SPA. I've added it as a comment to the issue that tracks that group of features in the SPA repo at https://github.com/scholarslab/neatline-spa/issues/74.
