### ISSUE TITLE
Image-based Exhibit (no map) - need default view settings in exhibit settings

### ISSUE THREAD

**Issue by eam5** [performant-software/neatline-omeka-s#61]
For an exhibit with an image background instead of a map background, need some way to set the default zoom level for exhibit

**Comment by akstuhl** [comment]
This correctly notes the need for a yet-to-be-implemented feature (exhibit default zoom) in the SPA. I've added it as a comment on the issue in the SPA repo that tracks this feature set at https://github.com/scholarslab/neatline-spa/issues/74
