### ISSUE TITLE
Clicking from an open record setting to exhibit settings

### ISSUE THREAD

**Issue by eam5** [performant-software/neatline-omeka-s#63]
While in the Record settings, if I click on a record, or click on the corresponding geometry, it opens the record - thats great- but if I then click on 'Exhibit Settings' with the record still open, the record remains highlighted in the view box (with the title box visible).

Maybe the exhibit view should always revert to the default exhibit view (once these settings are added) when the 'Exhibit Settings' tab is open?

This occurs in both map and image based exhibits

**Comment by akstuhl** [comment]
This is a good proposal for a UX improvement that should be pretty straightforward to implement in the SPA. I've move the issue to the SPA repo at https://github.com/scholarslab/neatline-spa/issues/136.
