### ISSUE TITLE
Why does a user need to save a new record before drawing any geometry?

### ISSUE THREAD

**Issue by eam5** [performant-software/neatline-omeka-s#64]
When creating a new record, a user needs to first click save before the drawing tools appear - can these be visible initially when creating a new record? Currently seems like an extra step thats not user friendly.

**Comment by akstuhl** [comment]
This is a good UX consideration that should be kept in mind while improving the handoff between geometry-drawing and record saving in the SPA. I've created a corresponding issue for this one in the SPA repo at https://github.com/scholarslab/neatline-spa/issues/135.
