### ISSUE TITLE
Image-based exhibit: map layer button present after click on exhibit settings from records page

### ISSUE THREAD

**Issue by eam5** [performant-software/neatline-omeka-s#65]
The map layer button appears in the top right after changing pages from the "Records" page to the "Exhibit Settings" page. The icon does not go away after this, and appears on every page. When present, a user can select the option 'DEFAULT Open Street Map', which puts the map behind the image, with no way to remove. No map options needed with Image based exhibits.

**Comment by eam5** [comment]
also... the map and layer icon is gone again after completely exiting the exhibit and returning

**Comment by akstuhl** [comment]
Thanks for documenting this bug. I've created a corresponding issue in the SPA repo at https://github.com/scholarslab/neatline-spa/issues/134.
