### ISSUE TITLE
Full-screen public view for exhibits?

### ISSUE THREAD

**Issue by eam5** [performant-software/neatline-omeka-s#66]
Is there a full-screen public view option available? Previous Neatline exhibits all had a link that added /fullscreen to the url to make the exhibit view full screen.

This link should be accessible from the public view page?

**Comment by akstuhl** [comment]
This is a great point and identifies a good low-hanging-fruit improvement. Fullscreen view via URL has actually been implemented in the Omeka S module — inserting "/full" after "/neatline" in the URL for any Neatline view will show it without the surrounding Omeka container — but this hasn't been reflected in the exhibit table. That should mainly be implemented on the SPA side, so I've opened a corresponding issue at https://github.com/scholarslab/neatline-spa/issues/133. That implementation may need supporting changes here, though, so this should be kept open for now.
