### ISSUE TITLE
Record Styles: Point Image not working

### ISSUE THREAD

**Issue by eam5** [performant-software/neatline-omeka-s#68]
Records->Style-> Imagery option for 'Point image' not working. Created a point (marker) on the map, and included an image url under 'point image' - point does not appear as image. 

Not sure how to use this Point Image option with the Leaflet drawing tools.

**Comment by akstuhl** [comment]
This correctly identifies a not-yet-implemented feature in the SPA, which is tracked at https://github.com/scholarslab/neatline-spa/issues/70. Closing for now as cross-repository duplicate.
